version: '2'
services:
  le:
    build:
      context: .
    environment:
      CRON_D_LE: |
        @monthly root (sv start syslog-ng || exit 1; /usr/local/bin/le renew) 2>&1 | logger --tag le-renew
        @reboot root (sv start syslog-ng || exit 1; /usr/local/bin/le --config /etc/opt/letsencrypt/standalone.ini --email webmaster@foobar.net.nz --domains foobar.net.nz,www.foobar.net.nz) 2>&1 | logger --tag le-reboot
